version: '3.8'

services:
  backend:
    build:
      context: ./konkursant-backend
      dockerfile: Dockerfile
    expose:
      - "8000"  # Открываем порт 8000 внутри сети Docker

  frontend:
    build:
      context: ./konkursant-frontend
      dockerfile: Dockerfile
    expose:
      - "80"  # Открываем порт 80 внутри сети Docker

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  
    depends_on:
      - frontend
      - backend
