version: '3.8'

services:
  backend:
    build:
      context: ./konkursant-backend
      dockerfile: Dockerfile
    volumes:
      - ./konkursant-backend/src:/app/src 
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./konkursant-frontend
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
